Repository nodejs/docker-node, pull requests merged in 2018-05, with the labels that each got.

#729 Introduce shfmt
  .travis.yml
  functions.sh
  generate-stackbrew-library.sh
  generate-stackbrew-pr.sh
  test-build.sh
  test-image.sh
  update.sh
Labels: enhancement

#730 Introduce EditorConfig
  .editorconfig
  .travis.yml
  docs/BestPractices.md
  update.sh
Labels: enhancement, help wanted

#749 Shush curl
  10/Dockerfile
  10/alpine/Dockerfile
  10/slim/Dockerfile
  10/stretch/Dockerfile
  6/Dockerfile
  6/alpine/Dockerfile
  6/slim/Dockerfile
  6/stretch/Dockerfile
  8/Dockerfile
  8/alpine/Dockerfile
  8/slim/Dockerfile
  8/stretch/Dockerfile
  9/Dockerfile
  9/alpine/Dockerfile
  9/slim/Dockerfile
  9/stretch/Dockerfile
  Dockerfile-alpine.template
  Dockerfile-slim.template
  Dockerfile-stretch.template
  Dockerfile.template
  chakracore/10/Dockerfile
  chakracore/8/Dockerfile
  chakracore/Dockerfile.template
Labels: enhancement

#755 Update for Node.js v10.2.0
  10/Dockerfile
  10/alpine/Dockerfile
  10/slim/Dockerfile
  10/stretch/Dockerfile
Labels: update

#756 Fix typo with ${IMAGES_FILE } variable reference
  generate-stackbrew-pr.sh
Labels: bug

#758 Update chakracore to v10.1.0 with Yarn v1.7.0
  chakracore/10/Dockerfile
Labels: update

#759 Update for Node.js v10.2.1
  10/Dockerfile
  10/alpine/Dockerfile
  10/slim/Dockerfile
  10/stretch/Dockerfile
Labels: update
